# Generated by Django 5.2.3 on 2025-06-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='applications/profile_photos/')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('profession', models.CharField(max_length=200)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('id_document_type', models.CharField(choices=[('nid', 'National ID (NID)'), ('birth_certificate', 'Birth Certificate'), ('passport', 'Passport')], max_length=20)),
                ('id_document_number', models.CharField(max_length=50)),
                ('id_document_photo', models.ImageField(blank=True, null=True, upload_to='applications/id_documents/')),
                ('holding_id_photo', models.ImageField(blank=True, null=True, upload_to='applications/holding_id/')),
                ('emergency_contact', models.CharField(max_length=200)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('has_motorbike', models.BooleanField(default=False)),
                ('motorcycle_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('motorcycle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('motorcycle_year', models.IntegerField(blank=True, null=True)),
                ('riding_experience', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-5 years)'), ('advanced', 'Advanced (5+ years)'), ('expert', 'Expert (10+ years)')], default='beginner', max_length=20)),
                ('citizenship_confirm', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
