# Generated by Django 5.2.3 on 2025-06-24 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_membershipapplication_user_rider_membership_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text="CSS class for icon (e.g., 'fas fa-discount', 'fas fa-gift')", max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for category', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Benefit Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='benefits/')),
                ('membership_level', models.CharField(choices=[('all', 'All Members'), ('basic', 'Basic Members'), ('premium', 'Premium Members'), ('vip', 'VIP Members')], default='all', max_length=20)),
                ('partner_name', models.CharField(blank=True, max_length=200)),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 15.50 for 15.5%', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount', max_digits=10, null=True)),
                ('contact_info', models.TextField(blank=True, help_text='Phone, email, website')),
                ('location', models.TextField(blank=True, help_text='Address or multiple locations')),
                ('website_url', models.URLField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum times a member can use this benefit', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured benefits section')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_zones', models.ManyToManyField(blank=True, help_text='Leave empty for all zones', to='riders.zone')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='riders.benefitcategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenefitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about usage')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='riders.benefit')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_usage', to='riders.rider')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
