# Generated by Django 5.2.3 on 2025-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_benefitcategory_benefit_benefitusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideevent',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='duration',
            field=models.CharField(blank=True, help_text="Event duration (e.g., '3 hours', '3 days, 2 nights')", max_length=100),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='For multi-day events', null=True),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description for event modal'),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='organizer_name',
            field=models.CharField(blank=True, help_text="Organization/team name (e.g., 'Dhaka Zone Team')", max_length=200),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs for completed events'),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='price',
            field=models.CharField(default='Free', help_text="Event price (e.g., 'Free', '৳500', '৳15,000')", max_length=100),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of requirements for the event'),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
