# Generated by Django 5.2.3 on 2025-06-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0006_rideevent_difficulty_rideevent_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideevent',
            name='full_description',
        ),
        migrations.AddField(
            model_name='rideevent',
            name='time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rideevent',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rideevent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Event price in BDT', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rideevent',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requirements for the event'),
        ),
    ]
