# Generated by Django 5.2.3 on 2025-06-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_remove_rideevent_full_description_rideevent_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideevent',
            name='difficulty',
        ),
    ]
