# Generated by Django 5.2.3 on 2025-06-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0008_remove_difficulty_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Upload event photos', upload_to='event_photos/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to='riders.rideevent')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='riders.rider')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
