# Generated by Django 5.2.3 on 2025-06-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0010_add_custom_user_type'),
        ('riders', '0010_notice'),
    ]

    operations = [
    ]
